# Generated by Django 3.1.7 on 2021-12-09 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_user_secret_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='secret_key',
        ),
    ]
